service: aws-build-xml-file

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
  exclude:
    - 'node_modules/**'
    - 'env/**'
    - 'package.json'
    - 'package-lock.json'
    - 'requirements.txt'
  include:
    - '*.py'

functions:
  build_xml:
    handler: src/build_xml.handler
    timeout: 500

resources:
  Resources:
    XMLFileBucketTesting:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: xml-file-uploading
